name: gmail_copy
description: A landing home page Gmail copy.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod:
  intl:
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - logo_gmail.png
    - dracula.png
    - avatar.png
    - tick.png
    - google_logo.png
